### ISSUE TITLE
Increase font size

### ISSUE THREAD

**Issue by Pimpao78** [jjk-code-otter/climate-indicator-manager#216]
Request to increase font size of x and Y-axis on regional temperature charts
https://jjk-code-otter.github.io/demo-dash/RegionalDashboard/dashboard.html 
![image](https://github.com/jjk-code-otter/climate-indicator-manager/assets/102362850/537da36a-e847-48cc-869c-71bd79087833)

**Comment by jjk-code-otter** [comment]
I increased the font size by around 50%, which is a bit more readable.

![WMO_RA_VI_Europe](https://github.com/jjk-code-otter/climate-indicator-manager/assets/108787685/7229bc51-44b5-4dd5-be46-b2636c9632aa)

**Comment by Pimpao78** [comment]
Looks great! Thanks John

**Comment by jjk-code-otter** [comment]
No problems. I'll merge this into the main code now.
